
<p>
    <?php 
    // echo $block->getTemp();?>
    <pre>
    <?php
    
    // print_r($block->helloWorld()); 
    ?>
    </pre>
    <?php 
                  $p = $block->getCollection();
                
                //   echo $p[0];
                // print_r($p[0]);

                //   echo "afdsfj  h";
        
    ?>
     <?php  
            // foreach($collection as $item){
            // 	echo $item[0];
            	
        
            // } exit(); 
            ?>
    

</p>