<?php

$infoViewModel = $block->getInfoViewModel();

?>
<?php if (!$block->canRegister() && $block->canShowInfoBlock()) : ?>
    <div class="block block-new-customer">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p><?= $block->escapeHtml(__('Sorry, the new account registration is disabled. You can contact us via email: revered@tech.com if you are interested.')) ?></p>
            
        </div>
    </div>
<?php endif; ?>