<?php

$entityId = $block->getEntityId() ? $block->getEntityId() : null;
if ($entityId):
    ?>
<fieldset class="fieldset admin__fieldset" id="sparsh_free_shipping_bar_entity_snippet_code_fieldset">
    <legend class="admin__legend legend">
        <span><?= $block->escapeHtml(__('Snippet Code')) ?></span>
    </legend><br/>
    <div>
        <div class="admin__field-control control">
            <div class="sparsh-free-shipping-bar-control-value">
                <p>Use the following code to show the shipping bar block in any place you want:</p>
                <strong>CMS Page/Static Block</strong>
                <pre class="sparsh-free-shipping-bar-snippet-code"><code>&#123;&#123;block class="Revered\Shippingbar\Block\Entity\FreeShippingBar" template="Sparsh_FreeShippingBar::free_shipping_bar.phtml" entity_id="<?= /* @noEscape */ $entityId ?>"&#125;&#125;</code></pre>
                <strong>Template .phtml file</strong>
                <pre class="sparsh-free-shipping-bar-snippet-code"><code>&lt;?= $block-&gt;getLayout()-&gt;createBlock("Revered\Shippingbar\Block\Entity\FreeShippingBar")-&gt;setTemplate("free_shipping_bar.phtml")-&gt;setEntityId("<?= /* @noEscape */ $entityId ?>")-&gt;toHtml();?&gt;</code></pre>
                <strong>Layout File</strong>
                <pre class="sparsh-free-shipping-bar-snippet-code"><code>&lt;block class="Revered\Shippingbar\Block\Entity\FreeShippingBar" name="sparsh.free-shipping.bar" template="Revered_Shippingbar::free_shipping_bar.phtml"&gt;<br/>&nbsp;&nbsp;&lt;arguments&gt; <br/>&nbsp;&nbsp;&nbsp;&nbsp;&lt;argument name="entity_id" xsi:type="string"><?= /* @noEscape */ $entityId ?>&lt;/argument&gt;<br/>&nbsp;&nbsp;&lt;/arguments&gt;<br/>&lt;/block&gt;</code></pre>
            </div>
        </div>
    </div>
</fieldset>
<?php endif; ?>
