<?php
    $collection = $block->getEditData();
?>
<h2 align="center"> Testimonial Edit</h2>

<form action="<?php echo $this->getUrl('revered/testimonial/save', ['_secure' => true]);?>" method="post">
<input type="hidden" name="post_id" id="post_id" value="<?= $collection['post_id']; ?>" />
    <table align="center">
        <tr>
        <label >Testimonial Title:</label><br>      
            <input type="text"  name="testimonial_title" value="<?= $collection['testimonial_title']; ?>"><br><br>
                
        </tr>
        <tr>
        <label >Testimonial Content:</label><br>      
            <input type="text"  name="testimonial_content" value="<?= $collection['testimonial_content']; ?>"><br><br>
            
        </tr>
          <tr>
          <label >Testimonial Date:</label><br>      
            <input type="date"  name="testimonial_date" value="<?= $collection['testimonial_date']; ?>"><br><br>
        </tr>
            <td ><input type="submit" value="update" name="submit"> </td>
        </tr>
    </table>
</form>