
<h2 align="center">add vehicle</h2>

<form action="<?php echo $this->getUrl('vehicle/revered/save', ['_secure' => true]);?>" method="post">

    <table align="center">
        <!-- <tr>
            <td>service_name:</td>
            <td><input type="text" name="service_name"> </td>
        </tr> -->
        <tr>
            <td>vehicle_type:</td>
            <td><input type="text" name="vehicle_type"> </td>
        </tr>
          <tr>
            <td>registration_date:</td>
            <td><input type="date" name="registration_date"> </td>
        </tr>
            <td colspan="4" align="center"><input type="submit" value="insert" name="submit"> </td>
        </tr>
    </table>
</form>