<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $block->getData('outputHelper');
$_imagehelper       = $this->helper('Magento\Catalog\Helper\Image');

$_config = $this->helper('Sm\Destino\Helper\Data');

$keep_ratio    = $_config->getCategoryView('keep_image');
$image_width   = $_config->getCategoryView('image_width');
$image_height  = $_config->getCategoryView('image_height');
$product_hover = $_config->getCategoryView('hover_image_effect');

$show_addtocart     = $_config->getAdvanced('show_addtocart_button');
$show_addtocompare  = $_config->getAdvanced('show_compare_button');
$show_addtowishlist = $_config->getAdvanced('show_wishlist_button');

$show_newlabel  = $_config->getAdvanced('show_newlabel');
$new_label_text = $_config->getAdvanced('new_label_text');

$show_salelabel  = $_config->getAdvanced('show_salelabel');
$sale_label_text = $_config->getAdvanced('sale_label_text');
$show_pecent     = $_config->getAdvanced('show_salediscount');

$homeStyle = $_config->getGeneral('home_style');

$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
    $imgClass = 'lazyload';
} else {
    $imgClass = '';
}

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="toolbar-top">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode        = 'grid';
        $image           = 'category_page_grid';
        $hover_image     = 'category_page_grid-hover';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode        = 'list';
        $image           = 'category_page_list';
        $hover_image     = 'category_page_list-hover';
        $showDescription = true;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = intval($block->getPositioned());
    ?>
    <div class="products wrapper category-product <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <?php if ($block->getMode() == 'grid') { ?>
            <ol class="grid-product-type products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="item-inner">
                            <div class="product-item-info" data-container="product-grid">
                                <?php $productImage = $block->getImage($_product, $image); ?>
                                <?php // Product Image ?>
                                <div class="product-item-image">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php
                                        if ($keep_ratio)
                                            $productImage = $_imagehelper->init($_product, $image)->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize($image_width);
                                        else
                                            $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                                        $productImageUrl = $productImage->getUrl();
                                        ?>

                                        <span class="product-image-wrapper">
											<img class="product-image-photo default_image <?php echo $imgClass; ?>"
												<?php if ($enableLadyLoading) { ?>
                                                    src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                    data-src="<?php echo $productImageUrl; ?>"
                                                <?php } else { ?>
                                                    src="<?php echo $productImageUrl; ?>"
                                                <?php } ?>

                                                 alt="<?php echo $productImage->getLabel(); ?>"
                                            />

											<?php if ($product_hover == 'second-image') { ?>
                                                <?php
                                                if ($keep_ratio)
                                                    $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize($image_width);
                                                else
                                                    $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);

                                                $productHoverImageUrl = $productHoverImage->getUrl();
                                                ?>

                                                <?php if ($productImageUrl != str_replace("/thumbnail/", "/small_image/", $productHoverImageUrl)): ?>
                                                    <img class="product-image-photo hover_image"
                                                         src="<?php echo $productHoverImageUrl; ?>"

														<?php if ($enableLadyLoading) { ?>
                                                            src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                            data-src="<?php echo $productHoverImageUrl; ?>"
                                                        <?php } else { ?>
                                                            src="<?php echo $productHoverImageUrl; ?>"
                                                        <?php } ?>

                                                         alt="<?php echo $productHoverImage->getLabel(); ?>"
                                                    />
                                                <?php endif; ?>
                                            <?php } ?>
										</span>

                                    </a>

                                    <?php if ($homeStyle == 'home-4' || $homeStyle == 'home-5' || $homeStyle == 'home-6' || $homeStyle == 'home-7' || $homeStyle == 'home-8' || $homeStyle == 'home-10') { ?>
                                        <div class="button-top">
                                            <?php if ($show_addtocart) { ?>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <a class="action tocart primary"
                                                           data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                           echo $block->getAddToCartUrl($_product) ?>"}}'
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </a>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData       = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                        ?>
                                                        <a class="action tocart primary"
                                                           data-post='<?php /* @escapeNotVerified */
                                                           echo $postData; ?>'
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable action tocart primary"><span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php } ?>

                                            <?php if ($show_addtowishlist) { ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Wish List') ?>">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>

                                            <?php if ($show_addtocompare) { ?>
                                                <?php if ($block->getAddToCompareUrl()): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Compare') ?>">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>
                                        </div>
                                    <?php } else { ?>
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($show_addtowishlist) { ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Wish List') ?>">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>

                                            <?php if ($show_addtocompare) { ?>
                                                <?php if ($block->getAddToCompareUrl()): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Compare') ?>">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>

                                    <!--Label-->
                                    <?php
                                    if ($show_newlabel) {
                                        $now      = date("Y-m-d");
                                        if ($_product->getData('news_from_date') && $_product->getData('news_to_date')) {
                                            $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                                            $newsTo   = substr($_product->getData('news_to_date'), 0, 10);

                                            if ($newsTo != '' || $newsFrom != '') {
                                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
                                                    echo '<div class="product-label new-label">' . $new_label_text . '</div>';
                                                }
                                            }
                                        }
                                    }

                                    if ($show_salelabel) {
                                        $orgprice        = $_product->getPrice();
                                        $specialprice    = $_product->getSpecialPrice();
                                        $specialfromdate = $_product->getSpecialFromDate();
                                        $specialtodate   = $_product->getSpecialToDate();
                                        $today           = time();

                                        if (!$specialprice)
                                            $specialprice = $orgprice;

                                        if ($specialprice < $orgprice) {
                                            if ((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
                                                if ($show_pecent) {
                                                    $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                                                    echo '<div class="product-label sale-label">' . '-' . $save_percent . '%' . '</div>';
                                                } else {
                                                    echo '<div class="product-label sale-label">' . $sale_label_text . '</div>';
                                                }
                                            }
                                        }
                                    }
                                    ?>
                                    <!--End label-->
                                </div>

                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <div class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </div>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php if ($_product->isSaleable() && !$this->helper('Adorncommerce\CallForPrice\Helper\Data')->isEnable($_product->getData('call_for_price_active'))): ?>
		                    <?php echo $block->getProductPrice($_product) ?>
	                        <?php endif; ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <?php if ($show_addtocart && ($homeStyle != 'home-4' && $homeStyle != 'home-5' && $homeStyle != 'home-6' && $homeStyle != 'home-7' && $homeStyle != 'home-8' && $homeStyle != 'home-10')) { ?>
                                        <div class="product-item-inner">
                                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form"
                                                              action="<?php /* @escapeNotVerified */
                                                              echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product"
                                                                   value="<?php /* @escapeNotVerified */
                                                                   echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */
                                                            echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                   value="<?php /* @escapeNotVerified */
                                                                   echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary">
																<span><?php /* @escapeNotVerified */
                                                                    echo __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                    echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable action tocart primary"><span><?php /* @escapeNotVerified */
                                                                    echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>

                                            </div>

                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>

        <?php } else { ?>
            <ol class="list-product-type products-list products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="item-inner">
                            <div class="product-item-info" data-container="product-grid">
                                <?php $productImage = $block->getImage($_product, $image); ?>
                                <?php // Product Image ?>
                                <div class="product-item-image">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php
                                        if ($keep_ratio)
                                            $productImage = $_imagehelper->init($_product, $image)->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize($image_width);
                                        else
                                            $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                                        $productImageUrl = $productImage->getUrl();
                                        ?>

                                        <span class="product-image-wrapper">
											<img class="product-image-photo default_image <?php echo $imgClass; ?>"
												<?php if ($enableLadyLoading) { ?>
                                                    src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                    data-src="<?php echo $productImageUrl; ?>"
                                                <?php } else { ?>
                                                    src="<?php echo $productImageUrl; ?>"
                                                <?php } ?>

                                                 alt="<?php echo $productImage->getLabel(); ?>"
                                            />

											<?php if ($product_hover == 'second-image') { ?>
                                                <?php
                                                if ($keep_ratio)
                                                    $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize($image_width);
                                                else
                                                    $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);

                                                $productHoverImageUrl = $productHoverImage->getUrl();
                                                ?>

                                                <?php if ($productImageUrl != str_replace("/thumbnail/", "/small_image/", $productHoverImageUrl)): ?>
                                                    <img class="product-image-photo hover_image"
                                                         src="<?php echo $productHoverImageUrl; ?>"

														<?php if ($enableLadyLoading) { ?>
                                                            src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                            data-src="<?php echo $productHoverImageUrl; ?>"
                                                        <?php } else { ?>
                                                            src="<?php echo $productHoverImageUrl; ?>"
                                                        <?php } ?>

                                                         alt="<?php echo $productHoverImage->getLabel(); ?>"
                                                    />
                                                <?php endif; ?>
                                            <?php } ?>
										</span>

                                    </a>

                                    <div data-role="add-to-links" class="actions-secondary">
                                        <?php if ($show_addtowishlist) { ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?php echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>

                                        <?php if ($show_addtocompare) { ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <span><?php echo __('Add to Compare') ?></span>
                                            </a>
                                        <?php } ?>
                                    </div>

                                    <!--Label-->
                                    <?php
                                    if ($show_newlabel) {
                                        $now      = date("Y-m-d");
                                        if ($_product->getData('news_from_date') && $_product->getData('news_to_date')) {
                                            $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                                            $newsTo   = substr($_product->getData('news_to_date'), 0, 10);

                                            if ($newsTo != '' || $newsFrom != '') {
                                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
                                                    echo '<div class="product-label new-label">' . $new_label_text . '</div>';
                                                }
                                            }
                                        }
                                    }

                                    if ($show_salelabel) {
                                        $orgprice        = $_product->getPrice();
                                        $specialprice    = $_product->getSpecialPrice();
                                        $specialfromdate = $_product->getSpecialFromDate();
                                        $specialtodate   = $_product->getSpecialToDate();
                                        $today           = time();

                                        if (!$specialprice)
                                            $specialprice = $orgprice;

                                        if ($specialprice < $orgprice) {
                                            if ((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
                                                if ($show_pecent) {
                                                    $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                                                    echo '<div class="product-label sale-label">' . '-' . $save_percent . '%' . '</div>';
                                                } else {
                                                    echo '<div class="product-label sale-label">' . $sale_label_text . '</div>';
                                                }
                                            }
                                        }
                                    }
                                    ?>
                                    <!--End label-->
                                </div>

                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <div class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </div>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>

                                    <?php if ($_product->isSaleable() && !$this->helper('Adorncommerce\CallForPrice\Helper\Data')->isEnable($_product->getData('call_for_price_active'))): ?>
		                    <?php echo $block->getProductPrice($_product) ?>
	                    <?php endif; ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <?php if ($show_addtocart) { ?>
                                        <div class="product-item-inner">
                                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form"
                                                              action="<?php /* @escapeNotVerified */
                                                              echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product"
                                                                   value="<?php /* @escapeNotVerified */
                                                                   echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */
                                                            echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                   value="<?php /* @escapeNotVerified */
                                                                   echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary">
																<span><?php /* @escapeNotVerified */
                                                                    echo __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                    echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable action tocart primary"><span><?php /* @escapeNotVerified */
                                                                    echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>

                                            </div>

                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php } ?>
    </div>
    <div class="toolbar-bottom">
        <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>